### ISSUE TITLE
README clarification

### ISSUE THREAD

**Issue by TheWilley** [mwalbeck/docker-flox#3]
In an attempt to make this docker image more approachable, you can make small tweaks to the README file. Some things I noticed during my installations attempts:

* The line `- /path/to/nginx:/etc/nginx:ro` in the Docker Compose example can be slightly confusing. According to [the official documentation](https://hub.docker.com/_/nginx), you should map a configuration file from the host to the Docker container like this: `/host/path/nginx.conf:/etc/nginx/nginx.conf:ro`. However, the example suggests mapping a folder instead, which is something you [shouldn't do](https://stackoverflow.com/a/57734960). To avoid confusion, you can update this line in the example to match the official documentation's approach, making it clear that we are looking for a configuration file.
* For those who are not familiar with Nginx, there's a chance they might not realize that the server attribute in the example configuration file should be placed within the http section of an Nginx configuration file, something I discovered [the hard way](https://stackoverflow.com/a/41766811). To provide clarity, you can add a note in the documentation to highlight that the server attribute belongs within the http section of the Nginx configuration file.

Please tell me if there's anything I've misunderstood.

**Comment by mwalbeck** [comment]
You're very much spot on with your feedback, and I've made the changes you suggested. Thank you!

Cheers!
